server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/accounts?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10  # Adjust based on your app's needs
      minimum-idle: 5         # Adjust based on your app's needs
      idle-timeout: 600000    # 10 minutes idle timeout
      max-lifetime: 1800000   # 30 minutes max lifetime of a connection

  jpa:
    hibernate:
      ddl-auto: update # Can also be `validate` or `none` for production
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  # Optional: To explicitly set your schema (if needed)
  # sql:
  #   init:
  #     platform: mysql
  #     schema-locations: classpath:db/schema.sql  # If you have a schema file
  #     data-locations: classpath:db/data.sql        # If you have data files
